
import React from 'react';
import { X, Scale, FileText, ShieldAlert } from 'lucide-react';

export type LegalType = 'tos' | 'privacy' | null;

interface LegalModalProps {
  type: LegalType;
  onClose: () => void;
}

const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;
  const isTos = type === 'tos';
  
  return (
    <div className="fixed inset-0 z-[300] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-white rounded-[2.5rem] w-full max-w-2xl max-h-[85vh] flex flex-col shadow-2xl animate-in zoom-in-95 overflow-hidden border-2 border-emerald-500/10">
        <div className="p-8 border-b border-gray-100 flex items-center justify-between shrink-0 bg-gray-50/50">
          <h3 className="text-2xl font-fredoka font-bold text-gray-800 flex items-center gap-3">
            {isTos ? <Scale className="text-emerald-500" /> : <FileText className="text-emerald-500" />}
            {isTos ? 'Advisor Terms of Service' : 'Advisor Privacy & Security'}
          </h3>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-xl text-gray-400 transition-colors">
            <X size={24} />
          </button>
        </div>
        
        <div className="p-8 overflow-y-auto font-sans text-sm text-gray-600 leading-relaxed space-y-6 no-scrollbar">
          {isTos ? (
            <>
              <section className="bg-emerald-50 p-5 rounded-2xl border border-emerald-100 mb-6">
                <div className="flex items-center gap-2 text-emerald-700 font-black text-[10px] uppercase tracking-widest mb-2">
                   <ShieldAlert size={14} /> 2026 VALID Compliance
                </div>
                <p className="text-xs text-emerald-800 font-medium">Accrue implements the VALID framework to ensure AI safety. All automated decisions are logged for forensic validation and include mandatory human sign-off checkpoints.</p>
              </section>
              <section>
                <h4 className="font-bold text-gray-800 mb-2">1. Forensic Benchmarking Scope</h4>
                <p>Accrue is an educational benchmarking platform. Our AI agents ("Advisors") provide strategic data analysis but lack the legal scope to execute trades or move capital independently.</p>
              </section>
              <section>
                <h4 className="font-bold text-gray-800 mb-2">2. Hallucination Disclaimer</h4>
                <p>While we use the VALID framework to prevent "lies" (hallucinations), all financial projections are experimental. Users must verify outputs with a certified professional before structural implementation.</p>
              </section>
            </>
          ) : (
            <>
              <section className="bg-blue-50 p-5 rounded-2xl border border-blue-100 mb-6">
                <div className="flex items-center gap-2 text-blue-700 font-black text-[10px] uppercase tracking-widest mb-2">
                   <ShieldAlert size={14} /> Data Insulation Protocol
                </div>
                <p className="text-xs text-blue-800 font-medium">Identifiers are pseudonymized before cloud processing. Real institutional names are tokenized to ensure sensitive data remains insulated from AI training models.</p>
              </section>
              <section>
                <h4 className="font-bold text-gray-800 mb-2">1. Encryption at Rest (GLBA)</h4>
                <p>Your master registry is secured using high-entropy encryption at rest. In accordance with GLBA Safeguards, your financial data is scrambled on your device using unique cryptographic keys.</p>
              </section>
              <section>
                <h4 className="font-bold text-gray-800 mb-2">2. Right to Explanation (GDPR Art. 22)</h4>
                <p>Users have the right to request a forensic trace (Audit ID) for any automated recommendation generated by our Senior Advisor AI.</p>
              </section>
            </>
          )}
          <div className="pt-8 text-center border-t border-gray-100">
            <p className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Framework: VALID ADMT Assessment v3.0 (2026)</p>
          </div>
        </div>
        
        <div className="p-8 border-t border-gray-50 shrink-0">
          <button 
            onClick={onClose}
            className="w-full bg-slate-900 text-white font-black py-5 rounded-[1.8rem] shadow-xl hover:bg-emerald-600 transition-all uppercase tracking-widest text-xs"
          >
            I CERTIFY AND AGREE
          </button>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
